#ifndef SEMANTIC_ANDROID_JAVAOPERATORENUM_HPP
#define SEMANTIC_ANDROID_JAVAOPERATORENUM_HPP

enum class JavaOperatorEnum {
    REACTFROMTRIGGER,
    TEACHBEHAVIOR,
    RESOLVECOMMAND,
    TEACHCONDITION,
    EXECUTEFROMCONDITION
};

#endif // SEMANTIC_ANDROID_JAVAOPERATORENUM_HPP
